### ISSUE TITLE
user code preference is not respected

### ISSUE THREAD

**Issue by wittjr** [ibm-apiconnect/devportal-addons#2]
The user preference does not seem to affect the default language shown in the code snippet.

Looks like there may be multiple issues as I found the apiexplorer.module always replacing the user preference with the default in the settings:
    // if user's default lang not set or is not one of the enabled ones then default to first enabled
    if (!isset($default_codesnippet_lang) || **!empty($default_codesnippet_lang)** || !in_array($default_codesnippet_lang, $codesnippet_langs)) {
      $default_codesnippet_lang = $first_enabled;
    }
I think that should be empty instead of !empty. Changing that seemed to get the correct language in the Drupal behaviors settings but did not seem to affect the actual rendered page.

Initially tried with apiconnect-explorer 4.1.73, updated to version 4.1.83 with no improvement.

**Comment by chrisdudley** [comment]
You're right, the PHP module had a bug there, I've fixed that, there was a similar bug in the v2018 code too which has also been fixed, and just to add to the fun there was a bug in explorer itself where it was ignoring the value that was passed in anyway!

The explorer part is being fixed now and should be published in the next day or 2. I'll leave this issue open until it has been published.

**Comment by redlanne** [comment]
fix is now published
